version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: betting
      POSTGRES_USER: botuser
      POSTGRES_PASSWORD: REPLACE_DB_PASSWORD
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend
  bot:
    build: .
    command: python -u bot/bot.py
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
      - CRYPTO_BOT_USERNAME=${CRYPTO_BOT_USERNAME}
    depends_on:
      - db
    networks:
      - backend
  worker:
    build: .
    command: python -u worker/watcher.py
    environment:
      - RPC_URL=${RPC_URL}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    networks:
      - backend
  admin:
    build: .
    command: gunicorn -w 2 admin.app:app -b 0.0.0.0:8000
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_SECRET=${ADMIN_SECRET}
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - backend
volumes:
  db_data:
networks:
  backend:
